"""Agent action executor.

Executes actions generated by agents — send notifications, create tasks,
update CRM records, trigger outreach sequences, and escalate issues.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Callable, Awaitable

import structlog

from app.services.agents.base_agent import ActionType, AgentAction

logger = structlog.get_logger(__name__)

ActionHandler = Callable[[AgentAction], Awaitable[dict[str, Any]]]


class ActionEngine:
    """Executes actions generated by the agent pipeline.

    Register custom handlers for each action type, or use the built-in
    defaults that log and return a confirmation payload.
    """

    def __init__(self) -> None:
        self._handlers: dict[ActionType, ActionHandler] = {
            ActionType.NOTIFY: self._handle_notify,
            ActionType.CREATE_TASK: self._handle_create_task,
            ActionType.UPDATE_DEAL: self._handle_update_deal,
            ActionType.TRIGGER_OUTREACH: self._handle_trigger_outreach,
            ActionType.ESCALATE: self._handle_escalate,
            ActionType.UPDATE_RECORD: self._handle_update_record,
            ActionType.GENERATE_REPORT: self._handle_generate_report,
        }
        self._execution_log: list[dict[str, Any]] = []
        self._max_log = 5000

    def register_handler(
        self,
        action_type: ActionType,
        handler: ActionHandler,
    ) -> None:
        """Register a custom handler for a specific action type."""
        self._handlers[action_type] = handler
        logger.info("action_engine.handler_registered", action_type=action_type.value)

    async def execute(self, action: AgentAction) -> dict[str, Any]:
        """Execute a single action and return the result."""
        handler = self._handlers.get(action.action_type)
        if not handler:
            logger.warning(
                "action_engine.no_handler",
                action_type=action.action_type.value,
            )
            return {"status": "skipped", "reason": "no handler registered"}

        start = datetime.utcnow()
        try:
            result = await handler(action)
            elapsed = (datetime.utcnow() - start).total_seconds() * 1000
            self._log_execution(action, result, elapsed, success=True)
            return result
        except Exception as exc:
            elapsed = (datetime.utcnow() - start).total_seconds() * 1000
            error_result = {"status": "error", "error": str(exc)}
            self._log_execution(action, error_result, elapsed, success=False)
            logger.error(
                "action_engine.execution_failed",
                action_type=action.action_type.value,
                error=str(exc),
            )
            return error_result

    async def execute_batch(
        self,
        actions: list[AgentAction],
        stop_on_error: bool = False,
    ) -> list[dict[str, Any]]:
        """Execute a batch of actions sequentially.

        Actions are executed in priority order (critical first).
        """
        priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        sorted_actions = sorted(
            actions,
            key=lambda a: priority_order.get(a.priority, 99),
        )

        results: list[dict[str, Any]] = []
        for action in sorted_actions:
            result = await self.execute(action)
            results.append(result)
            if stop_on_error and result.get("status") == "error":
                logger.warning("action_engine.batch_stopped_on_error")
                break

        return results

    def get_execution_log(self, limit: int = 100) -> list[dict[str, Any]]:
        return self._execution_log[-limit:]

    # ── Default handlers ─────────────────────────────────────────────────

    @staticmethod
    async def _handle_notify(action: AgentAction) -> dict[str, Any]:
        """Send a notification (email, Slack, in-app).

        In production, dispatches via the configured notification channels.
        """
        logger.info(
            "action_engine.notify",
            target=action.target_entity_id,
            priority=action.priority,
            message=action.payload.get("message", ""),
        )
        return {
            "status": "sent",
            "channel": action.payload.get("channel", "in_app"),
            "target": action.target_entity_id,
        }

    @staticmethod
    async def _handle_create_task(action: AgentAction) -> dict[str, Any]:
        """Create a task in the task management system.

        In production, integrates with CRM or internal task store.
        """
        logger.info(
            "action_engine.create_task",
            entity=action.target_entity_id,
            title=action.payload.get("title", action.rationale),
        )
        return {
            "status": "created",
            "task_title": action.payload.get("title", action.rationale),
            "assigned_to": action.payload.get("assigned_to"),
            "due_in_days": action.payload.get("due_in_days"),
        }

    @staticmethod
    async def _handle_update_deal(action: AgentAction) -> dict[str, Any]:
        """Update a deal record in the database.

        In production, writes to the deals table via the repository layer.
        """
        logger.info(
            "action_engine.update_deal",
            deal_id=action.target_entity_id,
            fields=list(action.payload.keys()),
        )
        return {
            "status": "updated",
            "deal_id": action.target_entity_id,
            "fields_updated": list(action.payload.keys()),
        }

    @staticmethod
    async def _handle_trigger_outreach(action: AgentAction) -> dict[str, Any]:
        """Trigger an outreach sequence.

        In production, creates an outreach sequence via the outreach service.
        """
        logger.info(
            "action_engine.trigger_outreach",
            company=action.payload.get("company_name"),
            channel=action.payload.get("channel"),
            template=action.payload.get("template"),
        )
        return {
            "status": "queued",
            "channel": action.payload.get("channel"),
            "template": action.payload.get("template"),
            "company_name": action.payload.get("company_name"),
        }

    @staticmethod
    async def _handle_escalate(action: AgentAction) -> dict[str, Any]:
        """Escalate an issue to management.

        In production, sends high-priority alerts and creates escalation records.
        """
        logger.warning(
            "action_engine.escalate",
            entity=action.target_entity_id,
            reason=action.payload.get("reason", action.rationale),
        )
        return {
            "status": "escalated",
            "entity_id": action.target_entity_id,
            "reason": action.payload.get("reason", action.rationale),
        }

    @staticmethod
    async def _handle_update_record(action: AgentAction) -> dict[str, Any]:
        """Update a generic entity record."""
        logger.info(
            "action_engine.update_record",
            entity_id=action.target_entity_id,
            entity_type=action.target_entity_type,
            fields=list(action.payload.keys()),
        )
        return {
            "status": "updated",
            "entity_id": action.target_entity_id,
            "entity_type": action.target_entity_type,
            "fields_updated": list(action.payload.keys()),
        }

    @staticmethod
    async def _handle_generate_report(action: AgentAction) -> dict[str, Any]:
        """Generate an analytical report."""
        logger.info(
            "action_engine.generate_report",
            report_type=action.payload.get("report_type"),
        )
        return {
            "status": "generated",
            "report_type": action.payload.get("report_type"),
        }

    # ── Internal ─────────────────────────────────────────────────────────

    def _log_execution(
        self,
        action: AgentAction,
        result: dict[str, Any],
        elapsed_ms: float,
        success: bool,
    ) -> None:
        entry = {
            "action_id": action.action_id,
            "action_type": action.action_type.value,
            "priority": action.priority,
            "target_entity": action.target_entity_id,
            "success": success,
            "result_status": result.get("status"),
            "elapsed_ms": round(elapsed_ms, 2),
            "timestamp": datetime.utcnow().isoformat(),
        }
        self._execution_log.append(entry)
        if len(self._execution_log) > self._max_log:
            self._execution_log = self._execution_log[-self._max_log:]
