/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Basic liveness probe — confirms the process is running.
         */
        get: operations["liveness_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe — verifies connectivity to Postgres and Redis.
         */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Source Freshness
         * @description Return freshness and health status for all configured data sources.
         */
        get: operations["data_source_freshness_api_v1_health_data_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/executive-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Executive Summary
         * @description Return the full executive dashboard payload.
         *
         *     Aggregates KPIs, forecasts, pipeline velocity, funnel, risk heatmap,
         *     and top/at-risk deal lists.  Placeholder data is returned until the
         *     analytics services are wired up.
         */
        get: operations["executive_summary_api_v1_dashboard_executive_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prospects
         * @description List prospects with filtering, sorting, and pagination.
         */
        get: operations["list_prospects_api_v1_prospects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prospects/{prospect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prospect
         * @description Retrieve full prospect detail by ID.
         */
        get: operations["get_prospect_api_v1_prospects__prospect_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prospects/{prospect_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Enrichment
         * @description Trigger asynchronous enrichment for a prospect.
         *
         *     Queues enrichment jobs for MCA, BSE/NSE, OGD, and other configured sources.
         */
        post: operations["trigger_enrichment_api_v1_prospects__prospect_id__enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deals
         * @description List deals with optional filters and pagination.
         */
        get: operations["list_deals_api_v1_deals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/risk-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deal Risk Summary
         * @description Return an aggregated risk view across all active deals.
         */
        get: operations["deal_risk_summary_api_v1_deals_risk_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deal
         * @description Retrieve full deal detail by ID.
         */
        get: operations["get_deal_api_v1_deals__deal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Data Sources
         * @description Return health and freshness for all configured data sources.
         */
        get: operations["list_data_sources_api_v1_data_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{source_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Health
         * @description Return health details for a single data source by name slug.
         */
        get: operations["get_source_health_api_v1_data_sources__source_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIResponse[DataProvenanceSummary] */
        APIResponse_DataProvenanceSummary_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["DataProvenanceSummary"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** APIResponse[DataSourceHealth] */
        APIResponse_DataSourceHealth_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["DataSourceHealth"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** APIResponse[DealDetail] */
        APIResponse_DealDetail_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["DealDetail"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** APIResponse[ExecutiveSummary] */
        APIResponse_ExecutiveSummary_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["ExecutiveSummary"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** APIResponse[ProspectDetail] */
        APIResponse_ProspectDetail_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["ProspectDetail"] | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** APIResponse[dict] */
        APIResponse_dict_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /**
         * CompetitorMention
         * @description A detected competitor mention within a deal context.
         */
        CompetitorMention: {
            /** Competitor Name */
            competitor_name: string;
            /** Source */
            source: string;
            /** Snippet */
            snippet: string;
            /** Sentiment */
            sentiment?: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /**
         * DataProvenanceSummary
         * @description Aggregate health overview across all data sources.
         */
        DataProvenanceSummary: {
            /** Sources */
            sources: components["schemas"]["DataSourceHealth"][];
            /**
             * Overall Health
             * @description healthy, degraded, or critical
             */
            overall_health: string;
            /**
             * Total Sources
             * @default 0
             */
            total_sources: number;
            /**
             * Healthy Count
             * @default 0
             */
            healthy_count: number;
            /**
             * Degraded Count
             * @default 0
             */
            degraded_count: number;
            /**
             * Down Count
             * @default 0
             */
            down_count: number;
            /**
             * Stale Count
             * @default 0
             */
            stale_count: number;
            /**
             * Last Checked
             * Format: date-time
             */
            last_checked?: string;
        };
        /**
         * DataSourceHealth
         * @description Health and performance metrics for a single data source.
         */
        DataSourceHealth: {
            /** Name */
            name: string;
            /**
             * Status
             * @description healthy, degraded, or down
             */
            status: string;
            /** Last Check */
            last_check?: string | null;
            /** Response Time Ms */
            response_time_ms?: number | null;
            /**
             * Error Rate
             * @default 0
             */
            error_rate: number;
            /**
             * Data Freshness
             * @description e.g. '45 minutes ago'
             */
            data_freshness?: string | null;
            /** Cache Hit Rate */
            cache_hit_rate?: number | null;
            /** Records Ingested */
            records_ingested?: number | null;
            /**
             * Tier
             * @description 1=Gov/Official, 2=Market, 3=Enrichment
             */
            tier: number;
        };
        /**
         * DealDetail
         * @description Full deal detail with risk analysis, engagement history, and recovery plays.
         */
        DealDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prospect Name */
            prospect_name: string;
            /** Stage */
            stage: string;
            /** Value Inr */
            value_inr: number;
            /** Risk Score */
            risk_score: number;
            /** Days In Stage */
            days_in_stage: number;
            /** Owner */
            owner?: string | null;
            /** Last Activity */
            last_activity?: string | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Win Probability */
            win_probability?: number | null;
            /** Engagement Score */
            engagement_score?: number | null;
            risk_factors?: components["schemas"]["DealRiskFactors"] | null;
            /** Engagement History */
            engagement_history?: components["schemas"]["EngagementEvent"][];
            stakeholder_coverage?: components["schemas"]["StakeholderCoverage"] | null;
            /** Competitor Mentions */
            competitor_mentions?: components["schemas"]["CompetitorMention"][];
            /** Recovery Plays */
            recovery_plays?: components["schemas"]["RecoveryPlay"][];
        };
        /**
         * DealRiskFactors
         * @description Individual risk factor breakdown for a deal.
         */
        DealRiskFactors: {
            /**
             * Engagement Momentum
             * @description Recent engagement velocity
             */
            engagement_momentum: number;
            /**
             * Stakeholder Coverage
             * @description Fraction of key stakeholders engaged
             */
            stakeholder_coverage: number;
            /**
             * Stage Velocity
             * @description Speed vs. historical avg for this stage
             */
            stage_velocity: number;
            /**
             * Sentiment Trend
             * @description Positive (1) to negative (-1)
             */
            sentiment_trend: number;
            /**
             * Competitor Presence
             * @description Strength of competitor involvement
             */
            competitor_presence: number;
            /**
             * Contract Value Drift
             * @description Change from initial quoted value
             */
            contract_value_drift: number;
        };
        /**
         * EngagementEvent
         * @description Logged engagement event on a deal.
         */
        EngagementEvent: {
            /** Event Type */
            event_type: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Description */
            description: string;
            /**
             * Sentiment
             * @description positive, neutral, or negative
             */
            sentiment?: string | null;
            /** Actor */
            actor?: string | null;
        };
        /**
         * EnrichmentEvent
         * @description Record of a data enrichment event.
         */
        EnrichmentEvent: {
            /** Source */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Fields Updated */
            fields_updated: string[];
            /** Success */
            success: boolean;
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * ErrorDetail
         * @description Structured error information.
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ExecutiveKPIs
         * @description Top-line KPIs for the executive dashboard.
         */
        ExecutiveKPIs: {
            arr: components["schemas"]["KPIMetric"];
            mrr: components["schemas"]["KPIMetric"];
            pipeline_value: components["schemas"]["KPIMetric"];
            win_rate: components["schemas"]["KPIMetric"];
            avg_deal_cycle: components["schemas"]["KPIMetric"];
            net_revenue_retention: components["schemas"]["KPIMetric"];
        };
        /**
         * ExecutiveSummary
         * @description Combined executive dashboard payload.
         */
        ExecutiveSummary: {
            kpis: components["schemas"]["ExecutiveKPIs"];
            /** Revenue Forecast */
            revenue_forecast: components["schemas"]["RevenueForecast"][];
            /** Pipeline Velocity */
            pipeline_velocity: components["schemas"]["PipelineVelocityData"][];
            funnel: components["schemas"]["FunnelData"];
            risk_heatmap: components["schemas"]["RiskHeatmapData"];
            /** Top Deals */
            top_deals: components["schemas"]["app__schemas__dashboard__DealSummary"][];
            /** At Risk Deals */
            at_risk_deals: components["schemas"]["app__schemas__dashboard__DealSummary"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Time Window
             * @default current_quarter
             */
            time_window: string;
        };
        /**
         * FinancialHealth
         * @description Financial health indicators for a prospect.
         */
        FinancialHealth: {
            /** Revenue Inr */
            revenue_inr?: number | null;
            /** Revenue Growth Pct */
            revenue_growth_pct?: number | null;
            /** Profit Margin Pct */
            profit_margin_pct?: number | null;
            /** Debt Equity Ratio */
            debt_equity_ratio?: number | null;
            /** Current Ratio */
            current_ratio?: number | null;
            /** Roe Pct */
            roe_pct?: number | null;
            /** Data Source */
            data_source?: string | null;
            /** As Of Date */
            as_of_date?: string | null;
        };
        /**
         * FunnelData
         * @description Full sales funnel with stage-by-stage breakdown.
         */
        FunnelData: {
            /** Stages */
            stages: components["schemas"]["FunnelStage"][];
            /** Overall Conversion */
            overall_conversion: number;
            /** Period */
            period: string;
        };
        /**
         * FunnelStage
         * @description A single stage in the sales funnel.
         */
        FunnelStage: {
            /** Stage Name */
            stage_name: string;
            /** Count */
            count: number;
            /** Value Inr */
            value_inr: number;
            /** Conversion Rate */
            conversion_rate: number;
        };
        /**
         * GrowthSignal
         * @description An individual growth signal detected for a prospect.
         */
        GrowthSignal: {
            /** Signal Type */
            signal_type: string;
            /** Description */
            description: string;
            /**
             * Strength
             * @description strong, moderate, or weak
             */
            strength: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Source */
            source?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KPIMetric
         * @description A single KPI metric with trend information and provenance.
         */
        KPIMetric: {
            /** Value */
            value: number;
            /** Formatted */
            formatted: string;
            /**
             * Trend Pct
             * @description Percentage change from prior period
             */
            trend_pct: number;
            /**
             * Trend Direction
             * @description up, down, or flat
             */
            trend_direction: string;
            /**
             * Is Positive
             * @description Whether the trend is favourable
             */
            is_positive: boolean;
            /**
             * Sparkline
             * @description Last N period values for inline chart
             */
            sparkline?: number[];
            /** Confidence */
            confidence: number;
            /** Source */
            source?: string | null;
            /** Last Updated */
            last_updated?: string | null;
        };
        /**
         * OutreachRecommendation
         * @description AI-generated outreach recommendation.
         */
        OutreachRecommendation: {
            /** Channel */
            channel: string;
            /** Timing */
            timing: string;
            /** Message Theme */
            message_theme: string;
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale?: string | null;
        };
        /** PaginatedResponse[DealSummary] */
        PaginatedResponse_DealSummary_: {
            /** Items */
            items: components["schemas"]["app__schemas__deals__DealSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /**
             * Pages
             * @default 1
             */
            pages: number;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /** PaginatedResponse[ProspectSummary] */
        PaginatedResponse_ProspectSummary_: {
            /** Items */
            items: components["schemas"]["ProspectSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /**
             * Pages
             * @default 1
             */
            pages: number;
            meta?: components["schemas"]["ResponseMetadata"];
        };
        /**
         * PipelineVelocityData
         * @description Pipeline velocity metrics per stage.
         */
        PipelineVelocityData: {
            /** Stage */
            stage: string;
            /** Deal Count */
            deal_count: number;
            /** Avg Value Inr */
            avg_value_inr: number;
            /** Avg Days In Stage */
            avg_days_in_stage: number;
            /** Conversion Rate */
            conversion_rate: number;
            /** Velocity Trend */
            velocity_trend: string;
        };
        /**
         * ProspectDetail
         * @description Full prospect detail with enrichment data, financials, and recommendations.
         */
        ProspectDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Industry */
            industry?: string | null;
            /** Nic Code */
            nic_code?: string | null;
            /**
             * Revenue Band Inr
             * @description e.g. '10-50 Cr'
             */
            revenue_band_inr?: string | null;
            /** Employee Count */
            employee_count?: number | null;
            /** State */
            state?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Last Enriched */
            last_enriched?: string | null;
            /** City */
            city?: string | null;
            /** Gst Number */
            gst_number?: string | null;
            /** Website */
            website?: string | null;
            /** Listed Exchange */
            listed_exchange?: string | null;
            /** Bse Code */
            bse_code?: string | null;
            /** Nse Symbol */
            nse_symbol?: string | null;
            /**
             * Dpiit Recognized
             * @default false
             */
            dpiit_recognized: boolean;
            financial_health?: components["schemas"]["FinancialHealth"] | null;
            /** Growth Signals */
            growth_signals?: components["schemas"]["GrowthSignal"][];
            /** Enrichment Timeline */
            enrichment_timeline?: components["schemas"]["EnrichmentEvent"][];
            /** Recommended Outreach */
            recommended_outreach?: components["schemas"]["OutreachRecommendation"][];
            /** Stakeholders */
            stakeholders?: components["schemas"]["Stakeholder"][];
        };
        /**
         * ProspectSummary
         * @description Compact prospect representation for list views.
         */
        ProspectSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string;
            /** Industry */
            industry?: string | null;
            /** Nic Code */
            nic_code?: string | null;
            /**
             * Revenue Band Inr
             * @description e.g. '10-50 Cr'
             */
            revenue_band_inr?: string | null;
            /** Employee Count */
            employee_count?: number | null;
            /** State */
            state?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Last Enriched */
            last_enriched?: string | null;
        };
        /**
         * RecoveryPlay
         * @description AI-recommended recovery action for an at-risk deal.
         */
        RecoveryPlay: {
            /** Action */
            action: string;
            /**
             * Priority
             * @description critical, high, medium, low
             */
            priority: string;
            /** Rationale */
            rationale: string;
            /** Expected Impact */
            expected_impact: string;
            /** Suggested Owner */
            suggested_owner?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /**
         * ResponseMetadata
         * @description Standard metadata attached to every API response.
         */
        ResponseMetadata: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Request Id */
            request_id?: string | null;
            /**
             * Data Freshness
             * @description Human-readable freshness, e.g. '2 hours ago'
             */
            data_freshness?: string | null;
            /** Source Attribution */
            source_attribution?: components["schemas"]["SourceAttribution"][];
            /** Confidence Score */
            confidence_score?: number | null;
            /**
             * Cache Status
             * @description HIT, MISS, or STALE
             */
            cache_status?: string | null;
        };
        /**
         * RevenueForecast
         * @description Revenue forecast with confidence intervals.
         */
        RevenueForecast: {
            /** Period */
            period: string;
            /** Forecast Value */
            forecast_value: number;
            /** Lower Bound */
            lower_bound: number;
            /** Upper Bound */
            upper_bound: number;
            /** Confidence Level */
            confidence_level: number;
            /** Model Version */
            model_version?: string | null;
        };
        /**
         * RiskHeatmapCell
         * @description Single cell in the deal risk heatmap.
         */
        RiskHeatmapCell: {
            /** Segment */
            segment: string;
            /** Risk Level */
            risk_level: string;
            /** Deal Count */
            deal_count: number;
            /** Total Value Inr */
            total_value_inr: number;
        };
        /**
         * RiskHeatmapData
         * @description Risk heatmap across segments and risk levels.
         */
        RiskHeatmapData: {
            /** Cells */
            cells: components["schemas"]["RiskHeatmapCell"][];
            /**
             * Risk Levels
             * @default [
             *       "low",
             *       "medium",
             *       "high",
             *       "critical"
             *     ]
             */
            risk_levels: string[];
        };
        /**
         * SourceAttribution
         * @description Provenance metadata for a data point.
         */
        SourceAttribution: {
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Reliability Tier
             * @description 1=Gov/Official, 2=Market, 3=Enrichment
             */
            reliability_tier: number;
        };
        /**
         * Stakeholder
         * @description Key stakeholder at a prospect company.
         */
        Stakeholder: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Department */
            department?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /**
             * Engagement Level
             * @description champion, supporter, neutral, blocker
             */
            engagement_level?: string | null;
            /** Last Contacted */
            last_contacted?: string | null;
        };
        /**
         * StakeholderCoverage
         * @description Stakeholder coverage summary for a deal.
         */
        StakeholderCoverage: {
            /** Total Identified */
            total_identified: number;
            /** Engaged */
            engaged: number;
            /** Champions */
            champions: number;
            /** Blockers */
            blockers: number;
            /** Neutral */
            neutral: number;
            /** Coverage Pct */
            coverage_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * DealSummary
         * @description Compact deal representation for dashboard widgets.
         */
        app__schemas__dashboard__DealSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prospect Name */
            prospect_name: string;
            /** Stage */
            stage: string;
            /** Value Inr */
            value_inr: number;
            /** Risk Score */
            risk_score: number;
            /** Days In Stage */
            days_in_stage: number;
            /** Owner */
            owner?: string | null;
        };
        /**
         * DealSummary
         * @description Compact deal representation for list views.
         */
        app__schemas__deals__DealSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prospect Name */
            prospect_name: string;
            /** Stage */
            stage: string;
            /** Value Inr */
            value_inr: number;
            /** Risk Score */
            risk_score: number;
            /** Days In Stage */
            days_in_stage: number;
            /** Owner */
            owner?: string | null;
            /** Last Activity */
            last_activity?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    data_source_freshness_api_v1_health_data_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_DataProvenanceSummary_"];
                };
            };
        };
    };
    executive_summary_api_v1_dashboard_executive_summary_get: {
        parameters: {
            query?: {
                /** @description current_quarter, last_quarter, ytd, custom */
                time_window?: string;
                /** @description Filter by Indian state or zone */
                territory?: string | null;
                /** @description Filter by industry segment */
                segment?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ExecutiveSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prospects_api_v1_prospects_get: {
        parameters: {
            query?: {
                industry?: string | null;
                state?: string | null;
                min_fit_score?: number | null;
                max_fit_score?: number | null;
                revenue_min_inr?: number | null;
                revenue_max_inr?: number | null;
                /** @description listed, unlisted, or all */
                listed_status?: string | null;
                sort_by?: string;
                sort_order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ProspectSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prospect_api_v1_prospects__prospect_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ProspectDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_enrichment_api_v1_prospects__prospect_id__enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deals_api_v1_deals_get: {
        parameters: {
            query?: {
                stage?: string | null;
                owner?: string | null;
                min_value?: number | null;
                max_value?: number | null;
                sort_by?: string;
                sort_order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DealSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_risk_summary_api_v1_deals_risk_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_dict_"];
                };
            };
        };
    };
    get_deal_api_v1_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_DealDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_data_sources_api_v1_data_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_DataProvenanceSummary_"];
                };
            };
        };
    };
    get_source_health_api_v1_data_sources__source_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_DataSourceHealth_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
